cmd_scripts/kconfig/qconf-moc.o := g++ -Wp,-MMD,scripts/kconfig/.qconf-moc.o.d -Wall -O2    -std=c++11 -fPIC -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/qt/QtGui -DQT_WIDGETS_LIB -I/usr/include/qt/QtWidgets -DQT_GUI_LIB -DQT_CORE_LIB -c -o scripts/kconfig/qconf-moc.o scripts/kconfig/qconf-moc.cc

source_scripts/kconfig/qconf-moc.o := scripts/kconfig/qconf-moc.cc

deps_scripts/kconfig/qconf-moc.o := \
  scripts/kconfig/qconf.h \
  /usr/include/qt/QtWidgets/QCheckBox \
  /usr/include/qt/QtWidgets/qcheckbox.h \
  /usr/include/qt/QtWidgets/qtwidgetsglobal.h \
  /usr/include/qt/QtGui/qtguiglobal.h \
  /usr/include/qt/QtCore/qglobal.h \
  /usr/include/qt/QtCore/qconfig.h \
  /usr/include/qt/QtCore/qtcore-config.h \
  /usr/include/qt/QtCore/qsystemdetection.h \
  /usr/include/qt/QtCore/qprocessordetection.h \
  /usr/include/qt/QtCore/qcompilerdetection.h \
  /usr/include/qt/QtCore/qtypeinfo.h \
  /usr/include/qt/QtCore/qsysinfo.h \
  /usr/include/qt/QtCore/qlogging.h \
  /usr/include/qt/QtCore/qflags.h \
  /usr/include/qt/QtCore/qatomic.h \
  /usr/include/qt/QtCore/qbasicatomic.h \
  /usr/include/qt/QtCore/qatomic_cxx11.h \
  /usr/include/qt/QtCore/qgenericatomic.h \
  /usr/include/qt/QtCore/qglobalstatic.h \
  /usr/include/qt/QtCore/qnumeric.h \
  /usr/include/qt/QtCore/qversiontagging.h \
  /usr/include/qt/QtGui/qtgui-config.h \
  /usr/include/qt/QtWidgets/qtwidgets-config.h \
  /usr/include/qt/QtWidgets/qabstractbutton.h \
  /usr/include/qt/QtGui/qicon.h \
  /usr/include/qt/QtCore/qsize.h \
  /usr/include/qt/QtCore/qnamespace.h \
  /usr/include/qt/QtCore/qmargins.h \
  /usr/include/qt/QtCore/qlist.h \
  /usr/include/qt/QtCore/qalgorithms.h \
  /usr/include/qt/QtCore/qiterator.h \
  /usr/include/qt/QtCore/qrefcount.h \
  /usr/include/qt/QtCore/qarraydata.h \
  /usr/include/qt/QtCore/qhashfunctions.h \
  /usr/include/qt/QtCore/qstring.h \
  /usr/include/qt/QtCore/qchar.h \
  /usr/include/qt/QtCore/qbytearray.h \
  /usr/include/qt/QtCore/qstringliteral.h \
  /usr/include/qt/QtCore/qstringalgorithms.h \
  /usr/include/qt/QtCore/qstringview.h \
  /usr/include/qt/QtCore/qpair.h \
  /usr/include/qt/QtCore/qvector.h \
  /usr/include/qt/QtCore/qcontainertools_impl.h \
  /usr/include/qt/QtCore/qbytearraylist.h \
  /usr/include/qt/QtCore/qstringlist.h \
  /usr/include/qt/QtCore/qregexp.h \
  /usr/include/qt/QtCore/qstringmatcher.h \
  /usr/include/qt/QtGui/qpixmap.h \
  /usr/include/qt/QtGui/qpaintdevice.h \
  /usr/include/qt/QtGui/qwindowdefs.h \
  /usr/include/qt/QtCore/qobjectdefs.h \
  /usr/include/qt/QtCore/qobjectdefs_impl.h \
  /usr/include/qt/QtCore/qrect.h \
  /usr/include/qt/QtCore/qpoint.h \
  /usr/include/qt/QtGui/qcolor.h \
  /usr/include/qt/QtGui/qrgb.h \
  /usr/include/qt/QtGui/qrgba64.h \
  /usr/include/qt/QtCore/qsharedpointer.h \
  /usr/include/qt/QtCore/qshareddata.h \
  /usr/include/qt/QtCore/qhash.h \
  /usr/include/qt/QtCore/qsharedpointer_impl.h \
  /usr/include/qt/QtCore/qobject.h \
  /usr/include/qt/QtCore/qscopedpointer.h \
  /usr/include/qt/QtCore/qmetatype.h \
  /usr/include/qt/QtCore/qvarlengtharray.h \
  /usr/include/qt/QtCore/qcontainerfwd.h \
  /usr/include/qt/QtCore/qobject_impl.h \
  /usr/include/qt/QtGui/qimage.h \
  /usr/include/qt/QtGui/qpixelformat.h \
  /usr/include/qt/QtGui/qtransform.h \
  /usr/include/qt/QtGui/qmatrix.h \
  /usr/include/qt/QtGui/qpolygon.h \
  /usr/include/qt/QtGui/qregion.h \
  /usr/include/qt/QtCore/qdatastream.h \
  /usr/include/qt/QtCore/qiodevice.h \
  /usr/include/qt/QtCore/qline.h \
  /usr/include/qt/QtGui/qkeysequence.h \
  /usr/include/qt/QtWidgets/qwidget.h \
  /usr/include/qt/QtGui/qpalette.h \
  /usr/include/qt/QtGui/qbrush.h \
  /usr/include/qt/QtGui/qfont.h \
  /usr/include/qt/QtGui/qfontmetrics.h \
  /usr/include/qt/QtGui/qfontinfo.h \
  /usr/include/qt/QtWidgets/qsizepolicy.h \
  /usr/include/qt/QtGui/qcursor.h \
  /usr/include/qt/QtWidgets/QDialog \
  /usr/include/qt/QtWidgets/qdialog.h \
  /usr/include/qt/QtWidgets/QHeaderView \
  /usr/include/qt/QtWidgets/qheaderview.h \
  /usr/include/qt/QtWidgets/qabstractitemview.h \
  /usr/include/qt/QtWidgets/qabstractscrollarea.h \
  /usr/include/qt/QtWidgets/qframe.h \
  /usr/include/qt/QtCore/qabstractitemmodel.h \
  /usr/include/qt/QtCore/qvariant.h \
  /usr/include/qt/QtCore/qmap.h \
  /usr/include/qt/QtCore/qitemselectionmodel.h \
  /usr/include/qt/QtCore/qset.h \
  /usr/include/qt/QtWidgets/qabstractitemdelegate.h \
  /usr/include/qt/QtWidgets/qstyleoption.h \
  /usr/include/qt/QtCore/qlocale.h \
  /usr/include/qt/QtWidgets/qabstractspinbox.h \
  /usr/include/qt/QtGui/qvalidator.h \
  /usr/include/qt/QtCore/qregularexpression.h \
  /usr/include/qt/QtWidgets/qslider.h \
  /usr/include/qt/QtWidgets/qabstractslider.h \
  /usr/include/qt/QtWidgets/qstyle.h \
  /usr/include/qt/QtWidgets/qtabbar.h \
  /usr/include/qt/QtWidgets/qtabwidget.h \
  /usr/include/qt/QtWidgets/qrubberband.h \
  /usr/include/qt/QtWidgets/QLineEdit \
  /usr/include/qt/QtWidgets/qlineedit.h \
  /usr/include/qt/QtGui/qtextcursor.h \
  /usr/include/qt/QtGui/qtextformat.h \
  /usr/include/qt/QtGui/qpen.h \
  /usr/include/qt/QtGui/qtextoption.h \
  /usr/include/qt/QtWidgets/QMainWindow \
  /usr/include/qt/QtWidgets/qmainwindow.h \
  /usr/include/qt/QtWidgets/QPushButton \
  /usr/include/qt/QtWidgets/qpushbutton.h \
  /usr/include/qt/QtCore/QSettings \
  /usr/include/qt/QtCore/qsettings.h \
  /usr/include/qt/QtWidgets/QSplitter \
  /usr/include/qt/QtWidgets/qsplitter.h \
  /usr/include/qt/QtWidgets/QStyledItemDelegate \
  /usr/include/qt/QtWidgets/qstyleditemdelegate.h \
  /usr/include/qt/QtWidgets/QTextBrowser \
  /usr/include/qt/QtWidgets/qtextbrowser.h \
  /usr/include/qt/QtWidgets/qtextedit.h \
  /usr/include/qt/QtGui/qtextdocument.h \
  /usr/include/qt/QtCore/qurl.h \
  /usr/include/qt/QtWidgets/QTreeWidget \
  /usr/include/qt/QtWidgets/qtreewidget.h \
  /usr/include/qt/QtWidgets/qtreeview.h \
  /usr/include/qt/QtWidgets/qtreewidgetitemiterator.h \
  scripts/kconfig/expr.h \
  scripts/kconfig/list.h \

scripts/kconfig/qconf-moc.o: $(deps_scripts/kconfig/qconf-moc.o)

$(deps_scripts/kconfig/qconf-moc.o):
