cmd_/home/joseph/Documents/linux-5.15.160/tools/bpf/resolve_btfids/main.o := gcc -Wp,-MD,/home/joseph/Documents/linux-5.15.160/tools/bpf/resolve_btfids/.main.o.d -Wp,-MT,/home/joseph/Documents/linux-5.15.160/tools/bpf/resolve_btfids/main.o -g -I/home/joseph/Documents/linux-5.15.160/tools/include -I/home/joseph/Documents/linux-5.15.160/tools/include/uapi -I/home/joseph/Documents/linux-5.15.160/tools/lib/bpf/ -I/home/joseph/Documents/linux-5.15.160/tools/lib/subcmd/ -D"BUILD_STR(s)=$(pound)s" -c -o /home/joseph/Documents/linux-5.15.160/tools/bpf/resolve_btfids/main.o main.c

source_/home/joseph/Documents/linux-5.15.160/tools/bpf/resolve_btfids/main.o := main.c

deps_/home/joseph/Documents/linux-5.15.160/tools/bpf/resolve_btfids/main.o := \
  /usr/include/stdc-predef.h \
  /usr/include/stdio.h \
  /usr/include/x86_64-linux-gnu/bits/libc-header-start.h \
  /usr/include/features.h \
  /usr/include/features-time64.h \
  /usr/include/x86_64-linux-gnu/bits/wordsize.h \
  /usr/include/x86_64-linux-gnu/bits/timesize.h \
  /usr/include/x86_64-linux-gnu/sys/cdefs.h \
  /usr/include/x86_64-linux-gnu/bits/long-double.h \
  /usr/include/x86_64-linux-gnu/gnu/stubs.h \
  /usr/include/x86_64-linux-gnu/gnu/stubs-64.h \
  /usr/lib/gcc/x86_64-linux-gnu/11/include/stddef.h \
  /usr/lib/gcc/x86_64-linux-gnu/11/include/stdarg.h \
  /usr/include/x86_64-linux-gnu/bits/types.h \
  /usr/include/x86_64-linux-gnu/bits/typesizes.h \
  /usr/include/x86_64-linux-gnu/bits/time64.h \
  /usr/include/x86_64-linux-gnu/bits/types/__fpos_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/__fpos64_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/__FILE.h \
  /usr/include/x86_64-linux-gnu/bits/types/FILE.h \
  /usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h \
  /usr/include/x86_64-linux-gnu/bits/types/cookie_io_functions_t.h \
  /usr/include/x86_64-linux-gnu/bits/stdio_lim.h \
  /usr/include/x86_64-linux-gnu/bits/floatn.h \
  /usr/include/x86_64-linux-gnu/bits/floatn-common.h \
  /usr/include/string.h \
  /usr/include/x86_64-linux-gnu/bits/types/locale_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/__locale_t.h \
  /usr/include/strings.h \
  /usr/include/unistd.h \
  /usr/include/x86_64-linux-gnu/bits/posix_opt.h \
  /usr/include/x86_64-linux-gnu/bits/environments.h \
  /usr/include/x86_64-linux-gnu/bits/confname.h \
  /usr/include/x86_64-linux-gnu/bits/getopt_posix.h \
  /usr/include/x86_64-linux-gnu/bits/getopt_core.h \
  /usr/include/x86_64-linux-gnu/bits/unistd_ext.h \
  /usr/include/linux/close_range.h \
  /usr/include/stdlib.h \
  /usr/include/x86_64-linux-gnu/bits/waitflags.h \
  /usr/include/x86_64-linux-gnu/bits/waitstatus.h \
  /usr/include/x86_64-linux-gnu/sys/types.h \
  /usr/include/x86_64-linux-gnu/bits/types/clock_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/clockid_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/time_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/timer_t.h \
  /usr/include/x86_64-linux-gnu/bits/stdint-intn.h \
  /usr/include/endian.h \
  /usr/include/x86_64-linux-gnu/bits/endian.h \
  /usr/include/x86_64-linux-gnu/bits/endianness.h \
  /usr/include/x86_64-linux-gnu/bits/byteswap.h \
  /usr/include/x86_64-linux-gnu/bits/uintn-identity.h \
  /usr/include/x86_64-linux-gnu/sys/select.h \
  /usr/include/x86_64-linux-gnu/bits/select.h \
  /usr/include/x86_64-linux-gnu/bits/types/sigset_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/__sigset_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/struct_timeval.h \
  /usr/include/x86_64-linux-gnu/bits/types/struct_timespec.h \
  /usr/include/x86_64-linux-gnu/bits/pthreadtypes.h \
  /usr/include/x86_64-linux-gnu/bits/thread-shared-types.h \
  /usr/include/x86_64-linux-gnu/bits/pthreadtypes-arch.h \
  /usr/include/x86_64-linux-gnu/bits/atomic_wide_counter.h \
  /usr/include/x86_64-linux-gnu/bits/struct_mutex.h \
  /usr/include/x86_64-linux-gnu/bits/struct_rwlock.h \
  /usr/include/alloca.h \
  /usr/include/x86_64-linux-gnu/bits/stdlib-float.h \
  /usr/include/libelf.h \
  /usr/lib/gcc/x86_64-linux-gnu/11/include/stdint.h \
  /usr/include/stdint.h \
  /usr/include/x86_64-linux-gnu/bits/wchar.h \
  /usr/include/x86_64-linux-gnu/bits/stdint-uintn.h \
  /usr/include/elf.h \
  /usr/include/gelf.h \
  /usr/include/x86_64-linux-gnu/sys/stat.h \
  /usr/include/x86_64-linux-gnu/bits/stat.h \
  /usr/include/x86_64-linux-gnu/bits/struct_stat.h \
  /usr/include/x86_64-linux-gnu/bits/statx.h \
  /home/joseph/Documents/linux-5.15.160/tools/include/uapi/linux/stat.h \
  /home/joseph/Documents/linux-5.15.160/tools/include/linux/types.h \
  /usr/lib/gcc/x86_64-linux-gnu/11/include/stdbool.h \
  /usr/include/x86_64-linux-gnu/asm/types.h \
  /usr/include/asm-generic/types.h \
  /usr/include/asm-generic/int-ll64.h \
  /home/joseph/Documents/linux-5.15.160/tools/include/uapi/asm/bitsperlong.h \
  /home/joseph/Documents/linux-5.15.160/tools/arch/x86/include/uapi/asm/bitsperlong.h \
  /home/joseph/Documents/linux-5.15.160/tools/include/asm-generic/bitsperlong.h \
  /home/joseph/Documents/linux-5.15.160/tools/include/uapi/asm-generic/bitsperlong.h \
  /usr/include/x86_64-linux-gnu/asm/posix_types.h \
  /usr/include/x86_64-linux-gnu/asm/posix_types_64.h \
  /usr/include/asm-generic/posix_types.h \
  /usr/include/x86_64-linux-gnu/bits/statx-generic.h \
  /usr/include/x86_64-linux-gnu/bits/types/struct_statx_timestamp.h \
  /usr/include/x86_64-linux-gnu/bits/types/struct_statx.h \
  /usr/include/fcntl.h \
  /usr/include/x86_64-linux-gnu/bits/fcntl.h \
  /usr/include/x86_64-linux-gnu/bits/fcntl-linux.h \
  /usr/include/x86_64-linux-gnu/bits/types/struct_iovec.h \
  /usr/include/linux/falloc.h \
  /usr/include/errno.h \
  /usr/include/x86_64-linux-gnu/bits/errno.h \
  /usr/include/linux/errno.h \
  /home/joseph/Documents/linux-5.15.160/tools/include/uapi/asm/errno.h \
  /home/joseph/Documents/linux-5.15.160/tools/arch/x86/include/uapi/asm/errno.h \
  /home/joseph/Documents/linux-5.15.160/tools/include/uapi/asm-generic/errno.h \
  /home/joseph/Documents/linux-5.15.160/tools/include/uapi/asm-generic/errno-base.h \
  /usr/include/x86_64-linux-gnu/bits/types/error_t.h \
  /home/joseph/Documents/linux-5.15.160/tools/include/linux/rbtree.h \
  /home/joseph/Documents/linux-5.15.160/tools/include/linux/kernel.h \
  /usr/include/assert.h \
  /home/joseph/Documents/linux-5.15.160/tools/include/linux/build_bug.h \
  /home/joseph/Documents/linux-5.15.160/tools/include/linux/compiler.h \
  /home/joseph/Documents/linux-5.15.160/tools/include/linux/compiler_types.h \
  /home/joseph/Documents/linux-5.15.160/tools/include/linux/compiler-gcc.h \
  /usr/include/byteswap.h \
  /usr/include/linux/stddef.h \
  /home/joseph/Documents/linux-5.15.160/tools/include/linux/zalloc.h \
  /home/joseph/Documents/linux-5.15.160/tools/include/linux/err.h \
  /home/joseph/Documents/linux-5.15.160/tools/lib/bpf/btf.h \
  /home/joseph/Documents/linux-5.15.160/tools/include/uapi/linux/btf.h \
  /home/joseph/Documents/linux-5.15.160/tools/lib/bpf/libbpf_common.h \
  /home/joseph/Documents/linux-5.15.160/tools/lib/bpf/libbpf.h \
  /home/joseph/Documents/linux-5.15.160/tools/include/uapi/linux/bpf.h \
  /home/joseph/Documents/linux-5.15.160/tools/include/uapi/linux/bpf_common.h \
  /home/joseph/Documents/linux-5.15.160/tools/lib/bpf/libbpf_legacy.h \
  /home/joseph/Documents/linux-5.15.160/tools/lib/subcmd/parse-options.h \

/home/joseph/Documents/linux-5.15.160/tools/bpf/resolve_btfids/main.o: $(deps_/home/joseph/Documents/linux-5.15.160/tools/bpf/resolve_btfids/main.o)

$(deps_/home/joseph/Documents/linux-5.15.160/tools/bpf/resolve_btfids/main.o):
